# config-apache/000-default.conf

ServerName localhost
ServerAdmin webmaster@localhost

# ==============================================================================
# CONFIGURACIÓN DE IP REAL (TRAEFIK -> APACHE)
# ==============================================================================
RemoteIPHeader X-Forwarded-For
RemoteIPInternalProxy 172.16.0.0/12 192.168.0.0/16 10.0.0.0/8 127.0.0.1

# ==============================================================================
# CONFIGURACIÓN DE LOGS EN JSON (Estilo DevOps Pro)
# ==============================================================================
# Construimos el JSON manualmente.
# %a: IP Real (gracias a RemoteIP)
# %t: Tiempo estándar
# %m: Método (GET, POST)
# %U%q: Path + Query
# %>s: Status Code
# %B: Bytes enviados (body)
# %D: Duración en microsegundos (¡Vital para performance!)
# %{Header}i: Cabeceras HTTP específicas

LogFormat "{ \
  \"time\": \"%{%Y-%m-%dT%H:%M:%S%z}t\", \
  \"remote_ip\": \"%a\", \
  \"host\": \"%{Host}i\", \
  \"method\": \"%m\", \
  \"uri\": \"%U%q\", \
  \"status\": %>s, \
  \"size_bytes\": %B, \
  \"duration_us\": %D, \
  \"referer\": \"%{Referer}i\", \
  \"user_agent\": \"%{User-agent}i\" \
}" json_combined

# Usamos el formato json_combined
ErrorLog /dev/stderr
CustomLog /dev/stdout json_combined env=!dontlog

# ==============================================================================
# CONFIGURACIÓN DEL DIRECTORIO Y PHP
# ==============================================================================

DocumentRoot ${APACHE_DOCUMENT_ROOT}

<Directory ${APACHE_DOCUMENT_ROOT}>
    AllowOverride All
    Require all granted
    Options -Indexes +FollowSymLinks -MultiViews
    DirectoryIndex index.php
</Directory>

# Healthchecks
ProxyPass "/healthcheck" "fcgi://localhost:9000"
ProxyPassReverse "/healthcheck" "fcgi://localhost:9000"

# PHP-FPM Proxy
<FilesMatch "\.php$">
    ProxyFCGIBackendType GENERIC
    SetHandler "proxy:fcgi://localhost:9000"
</FilesMatch>

ProxyTimeout 1800
SetEnvIf Request_URI "^${HEALTHCHECK_PATH}$" dontlog

ServerSignature Off
