[www]

; Redirect worker stdout and stderr into main error log. If not set, stdout and
; stderr will be redirected to /dev/null according to FastCGI specs.
catch_workers_output = yes

; Decorate worker output with prefix and suffix containing information about
; the child that writes to the log and if stdout or stderr is used as well as
; log level and time. Settings to "no" will output data as written to the
; stdout or stderr.
decorate_workers_output = no

; Remove error_log override to allow FPM master to catch errors via stderr pipe
; php_admin_value[error_log] = /proc/self/fd/2
php_admin_flag[log_errors] = on
